name: tiket_wisata
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  gap: ^3.0.1
  d_input: ^0.5.1
  concentric_transition: ^1.0.3
  flutter_animate: ^4.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
